import { Fragment } from "react";
import Head from "next/head";

export default function PageHeader({ title, icon }) {
  return (
    <Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex py-3">
        {icon}
        <h3 className="text-md font-medium leading-6 text-gray-900">{title}</h3>
      </div>
    </Fragment>
  );
}
