import Head from "next/head";
import { Fragment } from "react";

export default function PageHeader({ title, icon }) {
	return (
		<Fragment>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex py-3">
				{icon}
				<h3 className="text-md truncate font-bold leading-6 text-white">
					{title}
				</h3>
			</div>
		</Fragment>
	);
}
