import Head from "next/head";
import BlocksWidget from "../components/blocksWidget";
import TransfersWidget from "../components/transfersWidget";
import ChaindataWidget from "../components/chaindataWidget";

import { useGetLatestTenTransfersQuery } from "../libs/api/generated.ts";
import { usePolling } from "../libs/hooks/usePolling";

export default function Home({ transfersInitialData }) {
  const transfersQuery = usePolling(
    transfersInitialData,
    useGetLatestTenTransfersQuery
  );
  const transfers = transfersQuery?.transfers?.transfers;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="overflow-hidden lg:pb-32 xl:pb-36 ">
        <div className="mx-auto max-w-7xl py-3 px-4 sm:px-6 lg:px-8">
          <div className="grid gap-5 sm:grid-cols-1 md:grid-cols-1">
            <ChaindataWidget />
          </div>
        </div>
        <div className="mx-auto max-w-7xl py-3 px-4 sm:px-6 lg:px-8">
          <div className="grid gap-5 sm:grid-cols-1 md:grid-cols-2">
            <BlocksWidget />
            <TransfersWidget transfers={transfers} query={transfersQuery} />
          </div>
        </div>
      </div>
    </div>
  );
}
