name: Deploy | UAT
run-name: Deploy to `${{ github.event.inputs.branch }}` by @${{ github.actor }}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.branch }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        required: true
        description: Select a UAT branch
        options: ["", "uat/porcini"]
      commitSHA:
        type: string
        required: false
        description: "And input a valid commit SHA (40 chars string) to reset the UAT branch to \n(Optional: defaults to latest commit if empty)"
jobs:
  deploy_uat_head:
    if: github.event.inputs.commitSHA == ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and fetch main branch
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.repository.default_branch}}
      - name: Run the deployment using latest commit from default branch
        run: |
          echo "Using default branch: ${{github.event.repository.default_branch}}"
          git fetch
          git checkout ${{github.event.inputs.branch}}
          git reset --hard ${{github.event.repository.default_branch}}
          git push origin ${{github.event.inputs.branch}} --force-with-lease

  deploy_uat_sha:
    if: github.event.inputs.commitSHA != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and fetch using provided commit SHA
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.commitSHA}}
      - name: Run the deployment using provided commit SHA
        run: |
          echo "Using commit #: ${{github.event.inputs.commitSHA}}"
          git fetch
          git checkout ${{github.event.inputs.branch}}
          git reset --hard ${{github.event.inputs.commitSHA}}
          git push origin ${{github.event.inputs.branch}} --force-with-lease
